# Generated by Django 2.0.1 on 2018-01-04 08:24

from django.db import migrations
import pandas as pd
import numpy as np
from django.contrib.auth.models import User as UserD
from api.models import User


def migrate_data_users(apps, schema_editor):
    file = 'api/static/test_data.csv'
    df = pd.read_csv(file)
    print("loading data")
    for index, row in df.iterrows():
        username = row.get('username')
        password = username[::-1]
        email = row.get('email')
        created_at = row.get('created_at')
        last_login = row.get('last_login')

        user_django = UserD.objects.create_user(username=username, email=email, password=password)
        user_django.save()

        user = User()
        user.user = user_django
        user.created_at = created_at
        user.last_login = last_login
        user.save()

    #create admin user
    try:
        admin = UserD.objects.create_user(username="admin", email="admin@django.co", password="admin")
        admin.is_superuser = True
        admin.is_staff = True
        admin.save()
    except Exception as error:
        print("error: ", repr(error))
    print("migrate..ok")



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data_users), 
        ]
